
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "touch/src",
  "Ext.device.Purchases.Product": "touch/src/device/purchases/Sencha.js",
  "Ext.device.filesystem.DirectoryEntry": "touch/src/device/filesystem/HTML5.js",
  "Ext.device.filesystem.Entry": "touch/src/device/filesystem/HTML5.js",
  "Ext.device.filesystem.FileEntry": "touch/src/device/filesystem/HTML5.js",
  "Ext.device.filesystem.FileSystem": "touch/src/device/filesystem/HTML5.js",
  "Ext.device.purchases.Purchase": "touch/src/device/purchases/Sencha.js",
  "Ext.device.sqlite.Database": "touch/src/device/sqlite/Sencha.js",
  "Ext.device.sqlite.SQLResultSet": "touch/src/device/sqlite/Sencha.js",
  "Ext.device.sqlite.SQLResultSetRowList": "touch/src/device/sqlite/Sencha.js",
  "Ext.device.sqlite.SQLTransaction": "touch/src/device/sqlite/Sencha.js",
  "MyGPS": "app",
  "MyGPS.view.MultiPleTracking.API.MultipleTrackingAPI": "app/view/MultipleTracking/API/MultipleTrackingAPI.js",
  "MyGPS.view.MultiPleTracking.CustomePanel.MultiMapTrackingLayerNameCfmBox": "app/view/MultipleTracking/CustomePanel/MultiMapTrackingLayerNameCfmBox.js",
  "MyGPS.view.MultiPleTracking.CustomePanel.MultipleMapTrackingMenu": "app/view/MultipleTracking/CustomePanel/MultipleMapTrackingMenu.js",
  "MyGPS.view.MultiPleTracking.CustomePanel.MultipleMapTrackingSearchLocation": "app/view/MultipleTracking/CustomePanel/MultipleMapTrackingSearchLocation.js",
  "MyGPS.view.MultiPleTracking.CustomePanel.MultipleMapTrackingSettingLayer": "app/view/MultipleTracking/CustomePanel/MultipleMapTrackingSettingLayer.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Ext.AbstractComponent": [],
  "Ext.AbstractManager": [],
  "Ext.AbstractPlugin": [],
  "Ext.ActionSheet": [],
  "Ext.Ajax": [],
  "Ext.Anim": [],
  "Ext.AnimationQueue": [],
  "Ext.Audio": [],
  "Ext.BingMap": [],
  "Ext.Button": [],
  "Ext.Component": [
    "Ext.lib.Component"
  ],
  "Ext.ComponentManager": [
    "Ext.ComponentMgr"
  ],
  "Ext.ComponentQuery": [],
  "Ext.Container": [
    "Ext.lib.Container"
  ],
  "Ext.Decorator": [],
  "Ext.Evented": [
    "Ext.EventedBase"
  ],
  "Ext.Img": [],
  "Ext.ItemCollection": [],
  "Ext.Label": [],
  "Ext.LoadMask": [],
  "Ext.Map": [],
  "Ext.Mask": [],
  "Ext.Media": [],
  "Ext.Menu": [],
  "Ext.MessageBox": [],
  "Ext.Panel": [
    "Ext.lib.Panel"
  ],
  "Ext.ProgressIndicator": [],
  "Ext.Promise": [],
  "Ext.SegmentedButton": [],
  "Ext.Sheet": [],
  "Ext.Sortable": [],
  "Ext.Spacer": [],
  "Ext.TaskQueue": [],
  "Ext.Template": [],
  "Ext.Title": [],
  "Ext.TitleBar": [],
  "Ext.Toast": [],
  "Ext.Toolbar": [],
  "Ext.Video": [],
  "Ext.XTemplate": [],
  "Ext.XTemplateCompiler": [],
  "Ext.XTemplateParser": [],
  "Ext.app.Action": [],
  "Ext.app.Application": [],
  "Ext.app.Controller": [],
  "Ext.app.History": [],
  "Ext.app.Profile": [],
  "Ext.app.Route": [],
  "Ext.app.Router": [],
  "Ext.behavior.Behavior": [],
  "Ext.behavior.Draggable": [],
  "Ext.behavior.Scrollable": [],
  "Ext.behavior.Translatable": [],
  "Ext.carousel.Carousel": [
    "Ext.Carousel"
  ],
  "Ext.carousel.Indicator": [
    "Ext.Carousel.Indicator"
  ],
  "Ext.carousel.Infinite": [],
  "Ext.carousel.Item": [],
  "Ext.data.ArrayStore": [],
  "Ext.data.Batch": [],
  "Ext.data.Connection": [],
  "Ext.data.DirectStore": [],
  "Ext.data.Error": [],
  "Ext.data.Errors": [],
  "Ext.data.Field": [],
  "Ext.data.JsonP": [
    "Ext.util.JSONP"
  ],
  "Ext.data.JsonStore": [],
  "Ext.data.Model": [
    "Ext.data.Record"
  ],
  "Ext.data.ModelManager": [
    "Ext.ModelMgr",
    "Ext.ModelManager"
  ],
  "Ext.data.NodeInterface": [
    "Ext.data.Node"
  ],
  "Ext.data.NodeStore": [],
  "Ext.data.Operation": [],
  "Ext.data.Request": [],
  "Ext.data.ResultSet": [],
  "Ext.data.SortTypes": [],
  "Ext.data.Store": [],
  "Ext.data.StoreManager": [
    "Ext.StoreMgr",
    "Ext.data.StoreMgr",
    "Ext.StoreManager"
  ],
  "Ext.data.TreeStore": [],
  "Ext.data.Types": [],
  "Ext.data.Validations": [
    "Ext.data.validations"
  ],
  "Ext.data.association.Association": [
    "Ext.data.Association"
  ],
  "Ext.data.association.BelongsTo": [
    "Ext.data.BelongsToAssociation"
  ],
  "Ext.data.association.HasMany": [
    "Ext.data.HasManyAssociation"
  ],
  "Ext.data.association.HasOne": [
    "Ext.data.HasOneAssociation"
  ],
  "Ext.data.identifier.Sequential": [],
  "Ext.data.identifier.Simple": [],
  "Ext.data.identifier.Uuid": [],
  "Ext.data.plugin.Buffered": [],
  "Ext.data.proxy.Ajax": [
    "Ext.data.HttpProxy",
    "Ext.data.AjaxProxy"
  ],
  "Ext.data.proxy.Client": [
    "Ext.proxy.ClientProxy"
  ],
  "Ext.data.proxy.Direct": [
    "Ext.data.DirectProxy"
  ],
  "Ext.data.proxy.JsonP": [
    "Ext.data.ScriptTagProxy"
  ],
  "Ext.data.proxy.LocalStorage": [
    "Ext.data.LocalStorageProxy"
  ],
  "Ext.data.proxy.Memory": [
    "Ext.data.MemoryProxy"
  ],
  "Ext.data.proxy.Proxy": [
    "Ext.data.DataProxy",
    "Ext.data.Proxy"
  ],
  "Ext.data.proxy.Rest": [
    "Ext.data.RestProxy"
  ],
  "Ext.data.proxy.Server": [
    "Ext.data.ServerProxy"
  ],
  "Ext.data.proxy.SessionStorage": [
    "Ext.data.SessionStorageProxy"
  ],
  "Ext.data.proxy.Sql": [
    "Ext.data.proxy.SQL"
  ],
  "Ext.data.proxy.WebStorage": [
    "Ext.data.WebStorageProxy"
  ],
  "Ext.data.reader.Array": [
    "Ext.data.ArrayReader"
  ],
  "Ext.data.reader.Json": [
    "Ext.data.JsonReader"
  ],
  "Ext.data.reader.Reader": [
    "Ext.data.Reader",
    "Ext.data.DataReader"
  ],
  "Ext.data.reader.Xml": [
    "Ext.data.XmlReader"
  ],
  "Ext.data.writer.Json": [
    "Ext.data.JsonWriter"
  ],
  "Ext.data.writer.Writer": [
    "Ext.data.DataWriter",
    "Ext.data.Writer"
  ],
  "Ext.data.writer.Xml": [
    "Ext.data.XmlWriter"
  ],
  "Ext.dataview.DataView": [
    "Ext.DataView"
  ],
  "Ext.dataview.IndexBar": [
    "Ext.IndexBar"
  ],
  "Ext.dataview.List": [
    "Ext.List"
  ],
  "Ext.dataview.ListItemHeader": [],
  "Ext.dataview.NestedList": [
    "Ext.NestedList"
  ],
  "Ext.dataview.component.Container": [],
  "Ext.dataview.component.DataItem": [],
  "Ext.dataview.component.ListItem": [],
  "Ext.dataview.component.SimpleListItem": [],
  "Ext.dataview.element.Container": [],
  "Ext.dataview.element.List": [],
  "Ext.device.Accelerometer": [],
  "Ext.device.Browser": [],
  "Ext.device.Camera": [],
  "Ext.device.Capture": [],
  "Ext.device.Communicator": [],
  "Ext.device.Compass": [],
  "Ext.device.Connection": [],
  "Ext.device.Contacts": [],
  "Ext.device.Device": [],
  "Ext.device.FileSystem": [],
  "Ext.device.Geolocation": [],
  "Ext.device.Globalization": [],
  "Ext.device.Media": [],
  "Ext.device.Notification": [],
  "Ext.device.Orientation": [],
  "Ext.device.Purchases": [],
  "Ext.device.Purchases.Product": [],
  "Ext.device.Push": [],
  "Ext.device.SQLite": [],
  "Ext.device.Splashscreen": [],
  "Ext.device.Storage": [],
  "Ext.device.Tunnel": [],
  "Ext.device.accelerometer.Abstract": [],
  "Ext.device.accelerometer.Cordova": [
    "Ext.device.accelerometer.PhoneGap"
  ],
  "Ext.device.accelerometer.Simulator": [],
  "Ext.device.browser.Abstract": [],
  "Ext.device.browser.Cordova": [],
  "Ext.device.browser.Simulator": [],
  "Ext.device.browser.Window": [],
  "Ext.device.camera.Abstract": [],
  "Ext.device.camera.Cordova": [
    "Ext.device.camera.PhoneGap"
  ],
  "Ext.device.camera.Sencha": [],
  "Ext.device.camera.Simulator": [],
  "Ext.device.capture.Abstract": [
    "Ext.device.capture.Simulator"
  ],
  "Ext.device.capture.Cordova": [],
  "Ext.device.communicator.Android": [],
  "Ext.device.communicator.Default": [],
  "Ext.device.compass.Abstract": [],
  "Ext.device.compass.Cordova": [
    "Ext.device.compass.PhoneGap"
  ],
  "Ext.device.compass.Simulator": [],
  "Ext.device.connection.Abstract": [],
  "Ext.device.connection.Cordova": [
    "Ext.device.connection.PhoneGap"
  ],
  "Ext.device.connection.Sencha": [],
  "Ext.device.connection.Simulator": [],
  "Ext.device.contacts.Abstract": [],
  "Ext.device.contacts.Cordova": [
    "Ext.device.contacts.PhoneGap"
  ],
  "Ext.device.contacts.Sencha": [],
  "Ext.device.device.Abstract": [],
  "Ext.device.device.Cordova": [
    "Ext.device.device.PhoneGap"
  ],
  "Ext.device.device.Sencha": [],
  "Ext.device.device.Simulator": [],
  "Ext.device.filesystem.Abstract": [],
  "Ext.device.filesystem.Chrome": [],
  "Ext.device.filesystem.Cordova": [
    "Ext.device.filesystem.PhoneGap"
  ],
  "Ext.device.filesystem.DirectoryEntry": [],
  "Ext.device.filesystem.Entry": [],
  "Ext.device.filesystem.FileEntry": [],
  "Ext.device.filesystem.FileSystem": [],
  "Ext.device.filesystem.HTML5": [],
  "Ext.device.filesystem.Sencha": [],
  "Ext.device.filesystem.Simulator": [],
  "Ext.device.geolocation.Abstract": [],
  "Ext.device.geolocation.Cordova": [
    "Ext.device.geolocation.PhoneGap"
  ],
  "Ext.device.geolocation.Sencha": [],
  "Ext.device.geolocation.Simulator": [],
  "Ext.device.globalization.Abstract": [],
  "Ext.device.globalization.Cordova": [
    "Ext.device.globalization.PhoneGap"
  ],
  "Ext.device.globalization.Simulator": [],
  "Ext.device.media.Abstract": [],
  "Ext.device.media.Cordova": [
    "Ext.device.media.PhoneGap"
  ],
  "Ext.device.notification.Abstract": [],
  "Ext.device.notification.Cordova": [
    "Ext.device.notification.PhoneGap"
  ],
  "Ext.device.notification.Sencha": [],
  "Ext.device.notification.Simulator": [],
  "Ext.device.orientation.Abstract": [],
  "Ext.device.orientation.HTML5": [],
  "Ext.device.orientation.Sencha": [],
  "Ext.device.purchases.Purchase": [],
  "Ext.device.purchases.Sencha": [],
  "Ext.device.push.Abstract": [],
  "Ext.device.push.Cordova": [],
  "Ext.device.push.Sencha": [],
  "Ext.device.splashscreen.Abstract": [],
  "Ext.device.splashscreen.Cordova": [
    "Ext.device.splashscreen.PhoneGap"
  ],
  "Ext.device.splashscreen.Simulator": [],
  "Ext.device.sqlite.Database": [],
  "Ext.device.sqlite.SQLResultSet": [],
  "Ext.device.sqlite.SQLResultSetRowList": [],
  "Ext.device.sqlite.SQLTransaction": [],
  "Ext.device.sqlite.Sencha": [],
  "Ext.device.storage.Abstract": [],
  "Ext.device.storage.Cordova": [
    "Ext.device.storage.PhoneGap"
  ],
  "Ext.device.storage.HTML5.Database": [],
  "Ext.device.storage.HTML5.HTML5": [],
  "Ext.device.storage.HTML5.SQLStatement": [],
  "Ext.device.storage.Simulator": [],
  "Ext.device.tunnel.Abstract": [],
  "Ext.device.tunnel.Connection": [],
  "Ext.device.tunnel.Sencha": [],
  "Ext.device.tunnel.Simulator": [],
  "Ext.direct.Event": [],
  "Ext.direct.ExceptionEvent": [],
  "Ext.direct.JsonProvider": [],
  "Ext.direct.Manager": [
    "Ext.Direct"
  ],
  "Ext.direct.PollingProvider": [],
  "Ext.direct.Provider": [],
  "Ext.direct.RemotingEvent": [],
  "Ext.direct.RemotingMethod": [],
  "Ext.direct.RemotingProvider": [],
  "Ext.direct.Transaction": [
    "Ext.Direct.Transaction"
  ],
  "Ext.dom.CompositeElement": [
    "Ext.CompositeElement"
  ],
  "Ext.event.Controller": [],
  "Ext.event.Dispatcher": [],
  "Ext.event.Dom": [],
  "Ext.event.Event": [
    "Ext.EventObject"
  ],
  "Ext.event.ListenerStack": [],
  "Ext.event.Touch": [],
  "Ext.event.publisher.ComponentDelegation": [],
  "Ext.event.publisher.ComponentPaint": [],
  "Ext.event.publisher.ComponentSize": [],
  "Ext.event.publisher.Dom": [],
  "Ext.event.publisher.ElementPaint": [],
  "Ext.event.publisher.ElementSize": [],
  "Ext.event.publisher.Publisher": [],
  "Ext.event.publisher.TouchGesture": [],
  "Ext.event.recognizer.DoubleTap": [],
  "Ext.event.recognizer.Drag": [],
  "Ext.event.recognizer.EdgeSwipe": [],
  "Ext.event.recognizer.HorizontalSwipe": [],
  "Ext.event.recognizer.LongPress": [],
  "Ext.event.recognizer.MultiTouch": [],
  "Ext.event.recognizer.Pinch": [],
  "Ext.event.recognizer.Recognizer": [],
  "Ext.event.recognizer.Rotate": [],
  "Ext.event.recognizer.SingleTouch": [],
  "Ext.event.recognizer.Swipe": [],
  "Ext.event.recognizer.Tap": [],
  "Ext.event.recognizer.Touch": [],
  "Ext.event.recognizer.VerticalSwipe": [],
  "Ext.field.Checkbox": [
    "Ext.form.Checkbox"
  ],
  "Ext.field.DatePicker": [
    "Ext.form.DatePicker"
  ],
  "Ext.field.DatePickerNative": [
    "Ext.form.DatePickerNative"
  ],
  "Ext.field.Email": [
    "Ext.form.Email"
  ],
  "Ext.field.Field": [
    "Ext.form.Field"
  ],
  "Ext.field.File": [],
  "Ext.field.FileInput": [],
  "Ext.field.Hidden": [
    "Ext.form.Hidden"
  ],
  "Ext.field.Input": [],
  "Ext.field.Number": [
    "Ext.form.Number"
  ],
  "Ext.field.Password": [
    "Ext.form.Password"
  ],
  "Ext.field.Radio": [
    "Ext.form.Radio"
  ],
  "Ext.field.Search": [
    "Ext.form.Search"
  ],
  "Ext.field.Select": [
    "Ext.form.Select"
  ],
  "Ext.field.Slider": [
    "Ext.form.Slider"
  ],
  "Ext.field.Spinner": [
    "Ext.form.Spinner"
  ],
  "Ext.field.Text": [
    "Ext.form.Text"
  ],
  "Ext.field.TextArea": [
    "Ext.form.TextArea"
  ],
  "Ext.field.TextAreaInput": [],
  "Ext.field.Toggle": [
    "Ext.form.Toggle"
  ],
  "Ext.field.Url": [
    "Ext.form.Url"
  ],
  "Ext.form.FieldSet": [],
  "Ext.form.Panel": [
    "Ext.form.FormPanel"
  ],
  "Ext.fx.Animation": [],
  "Ext.fx.Easing": [],
  "Ext.fx.Runner": [],
  "Ext.fx.State": [],
  "Ext.fx.animation.Abstract": [],
  "Ext.fx.animation.Cube": [],
  "Ext.fx.animation.Fade": [
    "Ext.fx.animation.FadeIn"
  ],
  "Ext.fx.animation.FadeOut": [],
  "Ext.fx.animation.Flip": [],
  "Ext.fx.animation.Pop": [
    "Ext.fx.animation.PopIn"
  ],
  "Ext.fx.animation.PopOut": [],
  "Ext.fx.animation.Slide": [
    "Ext.fx.animation.SlideIn"
  ],
  "Ext.fx.animation.SlideOut": [],
  "Ext.fx.animation.Wipe": [
    "Ext.fx.animation.WipeIn"
  ],
  "Ext.fx.animation.WipeOut": [],
  "Ext.fx.easing.Abstract": [],
  "Ext.fx.easing.Bounce": [],
  "Ext.fx.easing.BoundMomentum": [],
  "Ext.fx.easing.EaseIn": [],
  "Ext.fx.easing.EaseOut": [],
  "Ext.fx.easing.Linear": [],
  "Ext.fx.easing.Momentum": [],
  "Ext.fx.layout.Card": [],
  "Ext.fx.layout.card.Abstract": [],
  "Ext.fx.layout.card.Cover": [],
  "Ext.fx.layout.card.Cube": [],
  "Ext.fx.layout.card.Fade": [],
  "Ext.fx.layout.card.Flip": [],
  "Ext.fx.layout.card.Pop": [],
  "Ext.fx.layout.card.Reveal": [],
  "Ext.fx.layout.card.Scroll": [],
  "Ext.fx.layout.card.ScrollCover": [],
  "Ext.fx.layout.card.ScrollReveal": [],
  "Ext.fx.layout.card.Slide": [],
  "Ext.fx.layout.card.Style": [],
  "Ext.fx.runner.Css": [],
  "Ext.fx.runner.CssAnimation": [],
  "Ext.fx.runner.CssTransition": [],
  "Ext.layout.Abstract": [],
  "Ext.layout.Box": [],
  "Ext.layout.Card": [],
  "Ext.layout.Default": [],
  "Ext.layout.Fit": [],
  "Ext.layout.FlexBox": [],
  "Ext.layout.Float": [],
  "Ext.layout.HBox": [],
  "Ext.layout.VBox": [],
  "Ext.layout.wrapper.BoxDock": [],
  "Ext.layout.wrapper.Dock": [],
  "Ext.layout.wrapper.Inner": [],
  "Ext.mixin.Bindable": [],
  "Ext.mixin.Filterable": [],
  "Ext.mixin.Mixin": [],
  "Ext.mixin.Observable": [
    "Ext.util.Observable"
  ],
  "Ext.mixin.Progressable": [],
  "Ext.mixin.Selectable": [],
  "Ext.mixin.Sortable": [],
  "Ext.mixin.Templatable": [],
  "Ext.mixin.Traversable": [],
  "Ext.navigation.Bar": [],
  "Ext.navigation.View": [
    "Ext.NavigationView"
  ],
  "Ext.picker.Date": [
    "Ext.DatePicker"
  ],
  "Ext.picker.Picker": [
    "Ext.Picker"
  ],
  "Ext.picker.Slot": [
    "Ext.Picker.Slot"
  ],
  "Ext.plugin.ListPaging": [],
  "Ext.plugin.PullRefresh": [],
  "Ext.plugin.SortableList": [],
  "Ext.scroll.Indicator": [
    "Ext.util.Indicator"
  ],
  "Ext.scroll.Scroller": [],
  "Ext.scroll.View": [
    "Ext.util.ScrollView"
  ],
  "Ext.scroll.indicator.Abstract": [],
  "Ext.scroll.indicator.CssTransform": [],
  "Ext.scroll.indicator.Rounded": [],
  "Ext.scroll.indicator.ScrollPosition": [],
  "Ext.slider.Slider": [],
  "Ext.slider.Thumb": [],
  "Ext.slider.Toggle": [],
  "Ext.tab.Bar": [
    "Ext.TabBar"
  ],
  "Ext.tab.Panel": [
    "Ext.TabPanel"
  ],
  "Ext.tab.Tab": [
    "Ext.Tab"
  ],
  "Ext.table.Cell": [],
  "Ext.table.Row": [],
  "Ext.table.Table": [],
  "Ext.util.AbstractMixedCollection": [],
  "Ext.util.Audio": [],
  "Ext.util.BufferedCollection": [],
  "Ext.util.Collection": [],
  "Ext.util.DelayedTask": [],
  "Ext.util.Draggable": [],
  "Ext.util.Droppable": [],
  "Ext.util.Filter": [],
  "Ext.util.Format": [],
  "Ext.util.Geolocation": [
    "Ext.util.GeoLocation"
  ],
  "Ext.util.Grouper": [],
  "Ext.util.HashMap": [],
  "Ext.util.Inflector": [],
  "Ext.util.InputBlocker": [],
  "Ext.util.LineSegment": [],
  "Ext.util.MixedCollection": [],
  "Ext.util.Offset": [],
  "Ext.util.PaintMonitor": [],
  "Ext.util.Point": [],
  "Ext.util.PositionMap": [],
  "Ext.util.Region": [],
  "Ext.util.SizeMonitor": [],
  "Ext.util.Sortable": [],
  "Ext.util.Sorter": [],
  "Ext.util.TapRepeater": [],
  "Ext.util.Translatable": [],
  "Ext.util.TranslatableGroup": [],
  "Ext.util.TranslatableList": [],
  "Ext.util.Wrapper": [],
  "Ext.util.paintmonitor.Abstract": [],
  "Ext.util.paintmonitor.CssAnimation": [],
  "Ext.util.paintmonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Abstract": [],
  "Ext.util.sizemonitor.Default": [],
  "Ext.util.sizemonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Scroll": [],
  "Ext.util.translatable.Abstract": [],
  "Ext.util.translatable.CssPosition": [],
  "Ext.util.translatable.CssTransform": [],
  "Ext.util.translatable.Dom": [],
  "Ext.util.translatable.ScrollPosition": [],
  "Ext.ux.ActionOverFlowMenuButton": [],
  "Ext.ux.ApplicationMenu": [],
  "Ext.ux.ContextMenu": [],
  "Ext.ux.MenuButton": [],
  "Ext.ux.TabMenuButton": [],
  "Ext.ux.device.Analytics": [],
  "Ext.ux.device.Twitter": [],
  "Ext.ux.device.analytics.Abstract": [],
  "Ext.ux.device.analytics.Cordova": [],
  "Ext.ux.device.twitter.Abstract": [],
  "Ext.ux.device.twitter.Cordova": [],
  "Ext.ux.parse.Helper": [
    "ParseHelper"
  ],
  "Ext.ux.parse.Model": [],
  "Ext.ux.parse.Proxy": [],
  "Ext.ux.parse.Reader": [],
  "Ext.ux.parse.Store": [],
  "Ext.ux.parse.association.Pointer": [],
  "Ext.ux.parse.association.Relation": [],
  "Ext.viewport.AndroidStock": [
    "Ext.viewport.Android"
  ],
  "Ext.viewport.Default": [],
  "Ext.viewport.Ios": [],
  "Ext.viewport.Viewport": [],
  "Ext.viewport.WindowsPhone": [
    "Ext.viewport.WP"
  ],
  "MyGPS.controller.MyController": [],
  "MyGPS.model.AlertMilageCount.alertMilageCount_LoadByDeviceAccNoModel": [],
  "MyGPS.model.AlertMilageCount.alertMilageCount_LoadReceiptPictureByIDModel": [],
  "MyGPS.model.AutoFenceTimerModel": [],
  "MyGPS.model.Building.BuildingGetAllModel": [],
  "MyGPS.model.Floor.FloorGetAllModel": [],
  "MyGPS.model.GPSuserModel": [],
  "MyGPS.model.GeofenceAlertHistory": [],
  "MyGPS.model.Layer.LayerBoundaryGetAllModel": [],
  "MyGPS.model.Layer.LayerGetAllModel": [],
  "MyGPS.model.ListOfMarkerModel": [],
  "MyGPS.model.MilageCountAlertHistory.MilageCountAlertHistory_LoadByDeviceAccNoModel": [],
  "MyGPS.model.MilageCountAlertHistory.MilageCountAlertHistory_LoadReceiptPictureByIDModel": [],
  "MyGPS.model.MilageCountInfo.MilageCountInfoLoad_ByAccountNoDeviceIDModel": [],
  "MyGPS.model.Place": [],
  "MyGPS.model.RegisterAccountModel": [],
  "MyGPS.model.RegisteredAccount.RegisteredAccountModel": [],
  "MyGPS.model.ResponderAlert.ResponderAlertModel": [],
  "MyGPS.model.ResponderAlertModel": [],
  "MyGPS.model.Sector.SectorGetAllModel": [],
  "MyGPS.model.Signal": [],
  "MyGPS.model.TraceAlert.TraceAlertHistoryModel": [],
  "MyGPS.model.TrackerDeviceModel": [],
  "MyGPS.model.TrackingHistory.TrackingHistoryModel": [],
  "MyGPS.model.TrackingItem": [],
  "MyGPS.model.TrackingItemAdjusted": [],
  "MyGPS.model.TrackingItemCheckIDmodel": [],
  "MyGPS.model.TrackingItemImage": [],
  "MyGPS.model.TrackingItemList.TrackingItemModel": [],
  "MyGPS.model.User.UserModel": [],
  "MyGPS.model.geoFenceAreaModel": [],
  "MyGPS.model.geoFenceModel": [],
  "MyGPS.model.markerModel": [],
  "MyGPS.model.multipleSignal": [],
  "MyGPS.model.multipletrackingsignal": [],
  "MyGPS.model.searchresultmodel": [],
  "MyGPS.model.settingModel": [],
  "MyGPS.model.signalhistorymodel": [],
  "MyGPS.model.signallastlocationmodel": [],
  "MyGPS.model.singlesignalTrackingmodel": [],
  "MyGPS.model.singlesignalmodel": [],
  "MyGPS.model.testlist": [],
  "MyGPS.store.AlertMilageCount.AlertMilageCountStore": [],
  "MyGPS.store.AutoFenceTimerGetByAcc": [],
  "MyGPS.store.AutoFenceTimerGetByID": [],
  "MyGPS.store.Building.BuildingStore": [],
  "MyGPS.store.Floor.FloorStore": [],
  "MyGPS.store.GPSuserStore": [],
  "MyGPS.store.GPSuserbyAccnostore": [],
  "MyGPS.store.GeofenceAlertHistoryGetByAcc": [],
  "MyGPS.store.GeofenceAlertHistoryStore": [],
  "MyGPS.store.GpsUser.GpsUserStore": [],
  "MyGPS.store.Layer.LayerGetAllStore": [],
  "MyGPS.store.ListofMarkerStore": [],
  "MyGPS.store.MarkerloadAllstore": [],
  "MyGPS.store.MilageCountAlertHistory.MilageCountAlertHistoryStore": [],
  "MyGPS.store.MilageCountInfo.MilageCountInfoStore": [],
  "MyGPS.store.Places": [],
  "MyGPS.store.RegisterAccountLatestIDstore": [],
  "MyGPS.store.RegisterAccountStore": [],
  "MyGPS.store.RegisteredAccount.RegisteredAccountStore": [],
  "MyGPS.store.ResponderAlert.ResponderAlertStore": [],
  "MyGPS.store.ResponderAlertGetByAcc": [],
  "MyGPS.store.ResponderAlertGetByID": [],
  "MyGPS.store.Sector.SectorStore": [],
  "MyGPS.store.SignalItemList": [],
  "MyGPS.store.TraceAlert.TraceAlertHistoryGetByAccNoTrackIDGeofenceID": [],
  "MyGPS.store.TraceAlert.TraceAlertHistoryGetByAccNoYearMonth": [],
  "MyGPS.store.TrackerDevicestore": [],
  "MyGPS.store.TrackingHistoryMap.TrackingHistoryMapStore": [],
  "MyGPS.store.TrackingItemCheckIDstore": [],
  "MyGPS.store.TrackingItemDetailstore": [],
  "MyGPS.store.TrackingItemImagestore": [],
  "MyGPS.store.TrackingItemList": [],
  "MyGPS.store.TrackingItemList.TrackingItemListsStore": [],
  "MyGPS.store.TrackingItemListAdjustedStore": [],
  "MyGPS.store.User.UserStore": [],
  "MyGPS.store.geoFenceActiveStore": [],
  "MyGPS.store.geoFenceAreaSelectByAccNo": [],
  "MyGPS.store.geoFenceAreaSelectByAccNoByFenceName": [],
  "MyGPS.store.geoFenceAreaSelectByIDByAccNo": [],
  "MyGPS.store.geoFenceStore": [],
  "MyGPS.store.getSearchColstore": [],
  "MyGPS.store.multipleSignalItemList": [],
  "MyGPS.store.multipletrackingitemselectF": [],
  "MyGPS.store.multipletrackingsignalpoint": [],
  "MyGPS.store.settingGetbyAccontNo": [],
  "MyGPS.store.signalhistorystore": [],
  "MyGPS.store.signallastlocationstore": [],
  "MyGPS.store.singlesignalTrackingstore": [],
  "MyGPS.store.singlesignalstore": [],
  "MyGPS.store.trackingitemhistorystore": [],
  "MyGPS.view.Config.MilageCountInfo.GetCurrentData": [],
  "MyGPS.view.Config.TrackingHistoryMap.TrackingHistoryMapConfig": [],
  "MyGPS.view.Config.TrackingItems.TrackingItemsConfig": [],
  "MyGPS.view.Config.User.UserConfig": [],
  "MyGPS.view.Login": [],
  "MyGPS.view.Main": [],
  "MyGPS.view.MainMenu": [],
  "MyGPS.view.MainMenuUpgrade": [],
  "MyGPS.view.MainPage": [],
  "MyGPS.view.MultiPleTracking.API.MultipleTrackingAPI": [],
  "MyGPS.view.MultiPleTracking.CustomePanel.MultiMapTrackingLayerNameCfmBox": [],
  "MyGPS.view.MultiPleTracking.CustomePanel.MultipleMapTrackingMenu": [],
  "MyGPS.view.MultiPleTracking.CustomePanel.MultipleMapTrackingSearchLocation": [],
  "MyGPS.view.MultiPleTracking.CustomePanel.MultipleMapTrackingSettingLayer": [],
  "MyGPS.view.MultipleTracking.multiTrackingItemsList": [],
  "MyGPS.view.MultipleTracking.multiTrackingMap": [],
  "MyGPS.view.MyAccount.RegistrationForm": [],
  "MyGPS.view.MyAccount.ResponderAlertList": [],
  "MyGPS.view.MyAccount.TrackieItems": [],
  "MyGPS.view.MyAccount.UserAcc": [],
  "MyGPS.view.MyAccount.listgeofTrackingitems": [],
  "MyGPS.view.MyAccount.singlesummary": [],
  "MyGPS.view.MyAccount.singlesummarypanel": [],
  "MyGPS.view.Setting.MainSetting": [],
  "MyGPS.view.Setting.MilageCountSetting": [],
  "MyGPS.view.Setting.SettingResponderAlert": [],
  "MyGPS.view.Setting.SettingTrackingItemList": [],
  "MyGPS.view.SettingFence.CustomePanel.SettingFenceAddNewfence": [],
  "MyGPS.view.SettingFence.CustomePanel.SettingFenceDrawFenceMenu": [],
  "MyGPS.view.SettingFence.CustomePanel.SettingFencePanelSettingInfo": [],
  "MyGPS.view.SettingFence.CustomePanel.SettingFencePanelSettingInfoSave": [],
  "MyGPS.view.SettingFence.CustomePanel.SettingFenceSearchLocation": [],
  "MyGPS.view.SettingFence.SettingFenceListOfGeoFence": [],
  "MyGPS.view.SettingFence.SettingFenceMap": [],
  "MyGPS.view.SingleTracking.CustomePanel.SingleTrackingMapVirtualFence_BurgerMenu": [],
  "MyGPS.view.SingleTracking.CustomePanel.SingleTrackingMap_PointInfo": [],
  "MyGPS.view.SingleTracking.CustomePanel.SingleTrackingWPSList": [],
  "MyGPS.view.SingleTracking.CustomePanel.SingleTrackingWPSListButton": [],
  "MyGPS.view.SingleTracking.SingleTrackingMapVirtualFence_Menus": [],
  "MyGPS.view.SingleTracking.holderSingleTrackingitem": [],
  "MyGPS.view.SingleTracking.listSingleTrackingitem": [],
  "MyGPS.view.SingleTracking.singleTrackingMap": [],
  "MyGPS.view.SingleTracking.singleTrackingOverViewMap": [],
  "MyGPS.view.SingleTrackingStreetView.SingleTrackingStreetViewMap": [],
  "MyGPS.view.TraceAlertFence.CustomePanel.TraceAlertFenceHistoryInfo": [],
  "MyGPS.view.TraceAlertFence.ListOfTraceAlertFence": [],
  "MyGPS.view.TraceAlertFence.TraceAlertFenceMap": [],
  "MyGPS.view.TrackingHistory.TrackingHistoryCreateria": [],
  "MyGPS.view.TrackingHistory.TrackingHistoryMap": [],
  "MyGPS.view.TrackingHistory.TrackingHistoryMapInfoPanel": [],
  "MyGPS.view.TrackingHistory.TrackingHistoryMapPlayTrackedPanel": [],
  "MyGPS.view.TrackingHistory.TrackingHistoryMapTravelRangePanel": [],
  "MyGPS.view.about.aboutapp": [],
  "MyGPS.view.about.abouts": [],
  "MyGPS.view.about.panelabout": [],
  "MyGPS.view.connection": [],
  "MyGPS.view.custompanel.SingelTrackingMap_MillageCount": [],
  "MyGPS.view.custompanel.SingelTrackingMap_MillageCountInfo": [],
  "MyGPS.view.custompanel.SingleTrackingMapStreetView_Menu": [],
  "MyGPS.view.custompanel.SingleTrackingMapStreetView_MiniMap": [],
  "MyGPS.view.custompanel.SingleTrackingMap_Menu": [],
  "MyGPS.view.custompanel.SingleTrackingMap_MilageCountAlertHistoryDetail": [],
  "MyGPS.view.custompanel.SingleTrackingMap_PointInfo": [],
  "MyGPS.view.custompanel.SingleTrackingMap_SpeedMeter": [],
  "MyGPS.view.custompanel.burgerMenu": [],
  "MyGPS.view.custompanel.dockOverViewMap": [],
  "MyGPS.view.custompanel.geofence_detailfencepanel": [],
  "MyGPS.view.custompanel.geofence_rightpanel": [],
  "MyGPS.view.custompanel.geofence_rightpanelSettingDrawFence": [],
  "MyGPS.view.custompanel.master_usermanual": [],
  "MyGPS.view.custompanel.multiTracking_InfoPanel": [],
  "MyGPS.view.custompanel.overViewMapStreetViewLiveTracking": [],
  "MyGPS.view.custompanel.singleStreetViewTrackingMap_rightpanel": [],
  "MyGPS.view.custompanel.singleTrackingMap_Search": [],
  "MyGPS.view.custompanel.singleTrackingMap_rightpanel": [],
  "MyGPS.view.custompanel.splashLogo": [],
  "MyGPS.view.functionality.funct": [],
  "MyGPS.view.functionality.routine": [],
  "MyGPS.view.geoFences.geoFenceDB": [],
  "MyGPS.view.geoFences.geofence": [],
  "MyGPS.view.geoFences.holdergeofence": [],
  "MyGPS.view.geoFences.listgeofenceArea": [],
  "MyGPS.view.geoFences.listgeofenceitem": [],
  "MyGPS.view.markerwithlabel": []
});
Ext.ClassManager.addNameAliasMappings({
  "Ext.AbstractComponent": [],
  "Ext.AbstractManager": [],
  "Ext.AbstractPlugin": [],
  "Ext.ActionSheet": [
    "widget.actionsheet"
  ],
  "Ext.Ajax": [],
  "Ext.Anim": [],
  "Ext.AnimationQueue": [],
  "Ext.Audio": [
    "widget.audio"
  ],
  "Ext.BingMap": [
    "widget.bingmap"
  ],
  "Ext.Button": [
    "widget.button"
  ],
  "Ext.Component": [
    "widget.component"
  ],
  "Ext.ComponentManager": [],
  "Ext.ComponentQuery": [],
  "Ext.Container": [
    "widget.container"
  ],
  "Ext.Decorator": [],
  "Ext.Evented": [],
  "Ext.Img": [
    "widget.image",
    "widget.img"
  ],
  "Ext.ItemCollection": [],
  "Ext.Label": [
    "widget.label"
  ],
  "Ext.LoadMask": [
    "widget.loadmask"
  ],
  "Ext.Map": [
    "widget.map"
  ],
  "Ext.Mask": [
    "widget.mask"
  ],
  "Ext.Media": [
    "widget.media"
  ],
  "Ext.Menu": [
    "widget.menu"
  ],
  "Ext.MessageBox": [],
  "Ext.Panel": [
    "widget.panel"
  ],
  "Ext.ProgressIndicator": [
    "widget.progressindicator"
  ],
  "Ext.Promise": [],
  "Ext.SegmentedButton": [
    "widget.segmentedbutton"
  ],
  "Ext.Sheet": [
    "widget.sheet"
  ],
  "Ext.Sortable": [],
  "Ext.Spacer": [
    "widget.spacer"
  ],
  "Ext.TaskQueue": [],
  "Ext.Template": [],
  "Ext.Title": [
    "widget.title"
  ],
  "Ext.TitleBar": [
    "widget.titlebar"
  ],
  "Ext.Toast": [],
  "Ext.Toolbar": [
    "widget.toolbar"
  ],
  "Ext.Video": [
    "widget.video"
  ],
  "Ext.XTemplate": [],
  "Ext.XTemplateCompiler": [],
  "Ext.XTemplateParser": [],
  "Ext.app.Action": [],
  "Ext.app.Application": [],
  "Ext.app.Controller": [],
  "Ext.app.History": [],
  "Ext.app.Profile": [],
  "Ext.app.Route": [],
  "Ext.app.Router": [],
  "Ext.behavior.Behavior": [],
  "Ext.behavior.Draggable": [],
  "Ext.behavior.Scrollable": [],
  "Ext.behavior.Translatable": [],
  "Ext.carousel.Carousel": [
    "widget.carousel"
  ],
  "Ext.carousel.Indicator": [
    "widget.carouselindicator"
  ],
  "Ext.carousel.Infinite": [],
  "Ext.carousel.Item": [],
  "Ext.data.ArrayStore": [
    "store.array"
  ],
  "Ext.data.Batch": [],
  "Ext.data.Connection": [],
  "Ext.data.DirectStore": [
    "store.direct"
  ],
  "Ext.data.Error": [],
  "Ext.data.Errors": [],
  "Ext.data.Field": [
    "data.field"
  ],
  "Ext.data.JsonP": [],
  "Ext.data.JsonStore": [
    "store.json"
  ],
  "Ext.data.Model": [],
  "Ext.data.ModelManager": [],
  "Ext.data.NodeInterface": [],
  "Ext.data.NodeStore": [
    "store.node"
  ],
  "Ext.data.Operation": [],
  "Ext.data.Request": [],
  "Ext.data.ResultSet": [],
  "Ext.data.SortTypes": [],
  "Ext.data.Store": [
    "store.store"
  ],
  "Ext.data.StoreManager": [],
  "Ext.data.TreeStore": [
    "store.tree"
  ],
  "Ext.data.Types": [],
  "Ext.data.Validations": [],
  "Ext.data.association.Association": [],
  "Ext.data.association.BelongsTo": [
    "association.belongsto"
  ],
  "Ext.data.association.HasMany": [
    "association.hasmany"
  ],
  "Ext.data.association.HasOne": [
    "association.hasone"
  ],
  "Ext.data.identifier.Sequential": [
    "data.identifier.sequential"
  ],
  "Ext.data.identifier.Simple": [
    "data.identifier.simple"
  ],
  "Ext.data.identifier.Uuid": [
    "data.identifier.uuid"
  ],
  "Ext.data.plugin.Buffered": [
    "plugin.storebuffered"
  ],
  "Ext.data.proxy.Ajax": [
    "proxy.ajax"
  ],
  "Ext.data.proxy.Client": [],
  "Ext.data.proxy.Direct": [
    "proxy.direct"
  ],
  "Ext.data.proxy.JsonP": [
    "proxy.jsonp",
    "proxy.scripttag"
  ],
  "Ext.data.proxy.LocalStorage": [
    "proxy.localstorage"
  ],
  "Ext.data.proxy.Memory": [
    "proxy.memory"
  ],
  "Ext.data.proxy.Proxy": [
    "proxy.proxy"
  ],
  "Ext.data.proxy.Rest": [
    "proxy.rest"
  ],
  "Ext.data.proxy.Server": [
    "proxy.server"
  ],
  "Ext.data.proxy.SessionStorage": [
    "proxy.sessionstorage"
  ],
  "Ext.data.proxy.Sql": [
    "proxy.sql"
  ],
  "Ext.data.proxy.WebStorage": [],
  "Ext.data.reader.Array": [
    "reader.array"
  ],
  "Ext.data.reader.Json": [
    "reader.json"
  ],
  "Ext.data.reader.Reader": [],
  "Ext.data.reader.Xml": [
    "reader.xml"
  ],
  "Ext.data.writer.Json": [
    "writer.json"
  ],
  "Ext.data.writer.Writer": [
    "writer.base"
  ],
  "Ext.data.writer.Xml": [
    "writer.xml"
  ],
  "Ext.dataview.DataView": [
    "widget.dataview"
  ],
  "Ext.dataview.IndexBar": [],
  "Ext.dataview.List": [
    "widget.list"
  ],
  "Ext.dataview.ListItemHeader": [
    "widget.listitemheader"
  ],
  "Ext.dataview.NestedList": [
    "widget.nestedlist"
  ],
  "Ext.dataview.component.Container": [],
  "Ext.dataview.component.DataItem": [
    "widget.dataitem"
  ],
  "Ext.dataview.component.ListItem": [
    "widget.listitem"
  ],
  "Ext.dataview.component.SimpleListItem": [
    "widget.simplelistitem"
  ],
  "Ext.dataview.element.Container": [],
  "Ext.dataview.element.List": [],
  "Ext.device.Accelerometer": [],
  "Ext.device.Browser": [],
  "Ext.device.Camera": [],
  "Ext.device.Capture": [],
  "Ext.device.Communicator": [],
  "Ext.device.Compass": [],
  "Ext.device.Connection": [],
  "Ext.device.Contacts": [],
  "Ext.device.Device": [],
  "Ext.device.FileSystem": [],
  "Ext.device.Geolocation": [],
  "Ext.device.Globalization": [],
  "Ext.device.Media": [],
  "Ext.device.Notification": [],
  "Ext.device.Orientation": [],
  "Ext.device.Purchases": [],
  "Ext.device.Purchases.Product": [],
  "Ext.device.Push": [],
  "Ext.device.SQLite": [],
  "Ext.device.Splashscreen": [],
  "Ext.device.Storage": [],
  "Ext.device.Tunnel": [],
  "Ext.device.accelerometer.Abstract": [],
  "Ext.device.accelerometer.Cordova": [],
  "Ext.device.accelerometer.Simulator": [],
  "Ext.device.browser.Abstract": [],
  "Ext.device.browser.Cordova": [],
  "Ext.device.browser.Simulator": [],
  "Ext.device.browser.Window": [],
  "Ext.device.camera.Abstract": [],
  "Ext.device.camera.Cordova": [],
  "Ext.device.camera.Sencha": [],
  "Ext.device.camera.Simulator": [],
  "Ext.device.capture.Abstract": [],
  "Ext.device.capture.Cordova": [],
  "Ext.device.communicator.Android": [],
  "Ext.device.communicator.Default": [],
  "Ext.device.compass.Abstract": [],
  "Ext.device.compass.Cordova": [],
  "Ext.device.compass.Simulator": [],
  "Ext.device.connection.Abstract": [],
  "Ext.device.connection.Cordova": [],
  "Ext.device.connection.Sencha": [],
  "Ext.device.connection.Simulator": [],
  "Ext.device.contacts.Abstract": [],
  "Ext.device.contacts.Cordova": [],
  "Ext.device.contacts.Sencha": [],
  "Ext.device.device.Abstract": [],
  "Ext.device.device.Cordova": [],
  "Ext.device.device.Sencha": [],
  "Ext.device.device.Simulator": [],
  "Ext.device.filesystem.Abstract": [],
  "Ext.device.filesystem.Chrome": [],
  "Ext.device.filesystem.Cordova": [],
  "Ext.device.filesystem.DirectoryEntry": [],
  "Ext.device.filesystem.Entry": [],
  "Ext.device.filesystem.FileEntry": [],
  "Ext.device.filesystem.FileSystem": [],
  "Ext.device.filesystem.HTML5": [],
  "Ext.device.filesystem.Sencha": [],
  "Ext.device.filesystem.Simulator": [],
  "Ext.device.geolocation.Abstract": [],
  "Ext.device.geolocation.Cordova": [],
  "Ext.device.geolocation.Sencha": [],
  "Ext.device.geolocation.Simulator": [],
  "Ext.device.globalization.Abstract": [],
  "Ext.device.globalization.Cordova": [],
  "Ext.device.globalization.Simulator": [],
  "Ext.device.media.Abstract": [],
  "Ext.device.media.Cordova": [],
  "Ext.device.notification.Abstract": [],
  "Ext.device.notification.Cordova": [],
  "Ext.device.notification.Sencha": [],
  "Ext.device.notification.Simulator": [],
  "Ext.device.orientation.Abstract": [],
  "Ext.device.orientation.HTML5": [],
  "Ext.device.orientation.Sencha": [],
  "Ext.device.purchases.Purchase": [],
  "Ext.device.purchases.Sencha": [],
  "Ext.device.push.Abstract": [],
  "Ext.device.push.Cordova": [],
  "Ext.device.push.Sencha": [],
  "Ext.device.splashscreen.Abstract": [],
  "Ext.device.splashscreen.Cordova": [],
  "Ext.device.splashscreen.Simulator": [],
  "Ext.device.sqlite.Database": [],
  "Ext.device.sqlite.SQLResultSet": [],
  "Ext.device.sqlite.SQLResultSetRowList": [],
  "Ext.device.sqlite.SQLTransaction": [],
  "Ext.device.sqlite.Sencha": [],
  "Ext.device.storage.Abstract": [],
  "Ext.device.storage.Cordova": [],
  "Ext.device.storage.HTML5.Database": [],
  "Ext.device.storage.HTML5.HTML5": [],
  "Ext.device.storage.HTML5.SQLStatement": [],
  "Ext.device.storage.Simulator": [],
  "Ext.device.tunnel.Abstract": [],
  "Ext.device.tunnel.Connection": [],
  "Ext.device.tunnel.Sencha": [],
  "Ext.device.tunnel.Simulator": [],
  "Ext.direct.Event": [
    "direct.event"
  ],
  "Ext.direct.ExceptionEvent": [
    "direct.exception"
  ],
  "Ext.direct.JsonProvider": [
    "direct.jsonprovider"
  ],
  "Ext.direct.Manager": [],
  "Ext.direct.PollingProvider": [
    "direct.pollingprovider"
  ],
  "Ext.direct.Provider": [
    "direct.provider"
  ],
  "Ext.direct.RemotingEvent": [
    "direct.rpc"
  ],
  "Ext.direct.RemotingMethod": [],
  "Ext.direct.RemotingProvider": [
    "direct.remotingprovider"
  ],
  "Ext.direct.Transaction": [
    "direct.transaction"
  ],
  "Ext.dom.CompositeElement": [],
  "Ext.event.Controller": [],
  "Ext.event.Dispatcher": [],
  "Ext.event.Dom": [],
  "Ext.event.Event": [],
  "Ext.event.ListenerStack": [],
  "Ext.event.Touch": [],
  "Ext.event.publisher.ComponentDelegation": [],
  "Ext.event.publisher.ComponentPaint": [],
  "Ext.event.publisher.ComponentSize": [],
  "Ext.event.publisher.Dom": [],
  "Ext.event.publisher.ElementPaint": [],
  "Ext.event.publisher.ElementSize": [],
  "Ext.event.publisher.Publisher": [],
  "Ext.event.publisher.TouchGesture": [],
  "Ext.event.recognizer.DoubleTap": [],
  "Ext.event.recognizer.Drag": [],
  "Ext.event.recognizer.EdgeSwipe": [],
  "Ext.event.recognizer.HorizontalSwipe": [],
  "Ext.event.recognizer.LongPress": [],
  "Ext.event.recognizer.MultiTouch": [],
  "Ext.event.recognizer.Pinch": [],
  "Ext.event.recognizer.Recognizer": [],
  "Ext.event.recognizer.Rotate": [],
  "Ext.event.recognizer.SingleTouch": [],
  "Ext.event.recognizer.Swipe": [],
  "Ext.event.recognizer.Tap": [],
  "Ext.event.recognizer.Touch": [],
  "Ext.event.recognizer.VerticalSwipe": [],
  "Ext.field.Checkbox": [
    "widget.checkboxfield"
  ],
  "Ext.field.DatePicker": [
    "widget.datepickerfield"
  ],
  "Ext.field.DatePickerNative": [
    "widget.datepickernativefield"
  ],
  "Ext.field.Email": [
    "widget.emailfield"
  ],
  "Ext.field.Field": [
    "widget.field"
  ],
  "Ext.field.File": [
    "widget.filefield"
  ],
  "Ext.field.FileInput": [
    "widget.fileinput"
  ],
  "Ext.field.Hidden": [
    "widget.hiddenfield"
  ],
  "Ext.field.Input": [
    "widget.input"
  ],
  "Ext.field.Number": [
    "widget.numberfield"
  ],
  "Ext.field.Password": [
    "widget.passwordfield"
  ],
  "Ext.field.Radio": [
    "widget.radiofield"
  ],
  "Ext.field.Search": [
    "widget.searchfield"
  ],
  "Ext.field.Select": [
    "widget.selectfield"
  ],
  "Ext.field.Slider": [
    "widget.sliderfield"
  ],
  "Ext.field.Spinner": [
    "widget.spinnerfield"
  ],
  "Ext.field.Text": [
    "widget.textfield"
  ],
  "Ext.field.TextArea": [
    "widget.textareafield"
  ],
  "Ext.field.TextAreaInput": [
    "widget.textareainput"
  ],
  "Ext.field.Toggle": [
    "widget.togglefield"
  ],
  "Ext.field.Url": [
    "widget.urlfield"
  ],
  "Ext.form.FieldSet": [
    "widget.fieldset"
  ],
  "Ext.form.Panel": [
    "widget.formpanel"
  ],
  "Ext.fx.Animation": [],
  "Ext.fx.Easing": [],
  "Ext.fx.Runner": [],
  "Ext.fx.State": [],
  "Ext.fx.animation.Abstract": [],
  "Ext.fx.animation.Cube": [
    "animation.cube"
  ],
  "Ext.fx.animation.Fade": [
    "animation.fade",
    "animation.fadeIn"
  ],
  "Ext.fx.animation.FadeOut": [
    "animation.fadeOut"
  ],
  "Ext.fx.animation.Flip": [
    "animation.flip"
  ],
  "Ext.fx.animation.Pop": [
    "animation.pop",
    "animation.popIn"
  ],
  "Ext.fx.animation.PopOut": [
    "animation.popOut"
  ],
  "Ext.fx.animation.Slide": [
    "animation.slide",
    "animation.slideIn"
  ],
  "Ext.fx.animation.SlideOut": [
    "animation.slideOut"
  ],
  "Ext.fx.animation.Wipe": [],
  "Ext.fx.animation.WipeOut": [],
  "Ext.fx.easing.Abstract": [],
  "Ext.fx.easing.Bounce": [],
  "Ext.fx.easing.BoundMomentum": [],
  "Ext.fx.easing.EaseIn": [
    "easing.ease-in"
  ],
  "Ext.fx.easing.EaseOut": [
    "easing.ease-out"
  ],
  "Ext.fx.easing.Linear": [
    "easing.linear"
  ],
  "Ext.fx.easing.Momentum": [],
  "Ext.fx.layout.Card": [],
  "Ext.fx.layout.card.Abstract": [],
  "Ext.fx.layout.card.Cover": [
    "fx.layout.card.cover"
  ],
  "Ext.fx.layout.card.Cube": [
    "fx.layout.card.cube"
  ],
  "Ext.fx.layout.card.Fade": [
    "fx.layout.card.fade"
  ],
  "Ext.fx.layout.card.Flip": [
    "fx.layout.card.flip"
  ],
  "Ext.fx.layout.card.Pop": [
    "fx.layout.card.pop"
  ],
  "Ext.fx.layout.card.Reveal": [
    "fx.layout.card.reveal"
  ],
  "Ext.fx.layout.card.Scroll": [
    "fx.layout.card.scroll"
  ],
  "Ext.fx.layout.card.ScrollCover": [
    "fx.layout.card.scrollcover"
  ],
  "Ext.fx.layout.card.ScrollReveal": [
    "fx.layout.card.scrollreveal"
  ],
  "Ext.fx.layout.card.Slide": [
    "fx.layout.card.slide"
  ],
  "Ext.fx.layout.card.Style": [],
  "Ext.fx.runner.Css": [],
  "Ext.fx.runner.CssAnimation": [],
  "Ext.fx.runner.CssTransition": [],
  "Ext.layout.Abstract": [],
  "Ext.layout.Box": [
    "layout.tablebox"
  ],
  "Ext.layout.Card": [
    "layout.card"
  ],
  "Ext.layout.Default": [
    "layout.auto",
    "layout.default"
  ],
  "Ext.layout.Fit": [
    "layout.fit"
  ],
  "Ext.layout.FlexBox": [
    "layout.box"
  ],
  "Ext.layout.Float": [
    "layout.float"
  ],
  "Ext.layout.HBox": [
    "layout.hbox"
  ],
  "Ext.layout.VBox": [
    "layout.vbox"
  ],
  "Ext.layout.wrapper.BoxDock": [],
  "Ext.layout.wrapper.Dock": [],
  "Ext.layout.wrapper.Inner": [],
  "Ext.mixin.Bindable": [],
  "Ext.mixin.Filterable": [],
  "Ext.mixin.Mixin": [],
  "Ext.mixin.Observable": [],
  "Ext.mixin.Progressable": [],
  "Ext.mixin.Selectable": [],
  "Ext.mixin.Sortable": [],
  "Ext.mixin.Templatable": [],
  "Ext.mixin.Traversable": [],
  "Ext.navigation.Bar": [],
  "Ext.navigation.View": [
    "widget.navigationview"
  ],
  "Ext.picker.Date": [
    "widget.datepicker"
  ],
  "Ext.picker.Picker": [
    "widget.picker"
  ],
  "Ext.picker.Slot": [
    "widget.pickerslot"
  ],
  "Ext.plugin.ListPaging": [
    "plugin.listpaging"
  ],
  "Ext.plugin.PullRefresh": [
    "plugin.pullrefresh"
  ],
  "Ext.plugin.SortableList": [
    "plugin.sortablelist"
  ],
  "Ext.scroll.Indicator": [],
  "Ext.scroll.Scroller": [],
  "Ext.scroll.View": [],
  "Ext.scroll.indicator.Abstract": [],
  "Ext.scroll.indicator.CssTransform": [],
  "Ext.scroll.indicator.Rounded": [],
  "Ext.scroll.indicator.ScrollPosition": [],
  "Ext.slider.Slider": [
    "widget.slider"
  ],
  "Ext.slider.Thumb": [
    "widget.thumb"
  ],
  "Ext.slider.Toggle": [],
  "Ext.tab.Bar": [
    "widget.tabbar"
  ],
  "Ext.tab.Panel": [
    "widget.tabpanel"
  ],
  "Ext.tab.Tab": [
    "widget.tab"
  ],
  "Ext.table.Cell": [
    "widget.tablecell"
  ],
  "Ext.table.Row": [
    "widget.tablerow"
  ],
  "Ext.table.Table": [
    "widget.table"
  ],
  "Ext.util.AbstractMixedCollection": [],
  "Ext.util.Audio": [],
  "Ext.util.BufferedCollection": [],
  "Ext.util.Collection": [],
  "Ext.util.DelayedTask": [],
  "Ext.util.Draggable": [],
  "Ext.util.Droppable": [],
  "Ext.util.Filter": [],
  "Ext.util.Format": [],
  "Ext.util.Geolocation": [],
  "Ext.util.Grouper": [],
  "Ext.util.HashMap": [],
  "Ext.util.Inflector": [],
  "Ext.util.InputBlocker": [],
  "Ext.util.LineSegment": [],
  "Ext.util.MixedCollection": [],
  "Ext.util.Offset": [],
  "Ext.util.PaintMonitor": [],
  "Ext.util.Point": [],
  "Ext.util.PositionMap": [],
  "Ext.util.Region": [],
  "Ext.util.SizeMonitor": [],
  "Ext.util.Sortable": [],
  "Ext.util.Sorter": [],
  "Ext.util.TapRepeater": [],
  "Ext.util.Translatable": [],
  "Ext.util.TranslatableGroup": [],
  "Ext.util.TranslatableList": [],
  "Ext.util.Wrapper": [],
  "Ext.util.paintmonitor.Abstract": [],
  "Ext.util.paintmonitor.CssAnimation": [],
  "Ext.util.paintmonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Abstract": [],
  "Ext.util.sizemonitor.Default": [],
  "Ext.util.sizemonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Scroll": [],
  "Ext.util.translatable.Abstract": [],
  "Ext.util.translatable.CssPosition": [],
  "Ext.util.translatable.CssTransform": [],
  "Ext.util.translatable.Dom": [],
  "Ext.util.translatable.ScrollPosition": [],
  "Ext.ux.ActionOverFlowMenuButton": [],
  "Ext.ux.ApplicationMenu": [],
  "Ext.ux.ContextMenu": [],
  "Ext.ux.MenuButton": [],
  "Ext.ux.TabMenuButton": [],
  "Ext.ux.device.Analytics": [],
  "Ext.ux.device.Twitter": [],
  "Ext.ux.device.analytics.Abstract": [],
  "Ext.ux.device.analytics.Cordova": [],
  "Ext.ux.device.twitter.Abstract": [],
  "Ext.ux.device.twitter.Cordova": [],
  "Ext.ux.parse.Helper": [],
  "Ext.ux.parse.Model": [],
  "Ext.ux.parse.Proxy": [
    "proxy.parse"
  ],
  "Ext.ux.parse.Reader": [
    "reader.parse"
  ],
  "Ext.ux.parse.Store": [],
  "Ext.ux.parse.association.Pointer": [
    "association.pointer"
  ],
  "Ext.ux.parse.association.Relation": [
    "association.relation"
  ],
  "Ext.viewport.AndroidStock": [],
  "Ext.viewport.Default": [
    "widget.viewport"
  ],
  "Ext.viewport.Ios": [],
  "Ext.viewport.Viewport": [],
  "Ext.viewport.WindowsPhone": [],
  "MyGPS.controller.MyController": [],
  "MyGPS.model.AlertMilageCount.alertMilageCount_LoadByDeviceAccNoModel": [],
  "MyGPS.model.AlertMilageCount.alertMilageCount_LoadReceiptPictureByIDModel": [],
  "MyGPS.model.AutoFenceTimerModel": [],
  "MyGPS.model.Building.BuildingGetAllModel": [],
  "MyGPS.model.Floor.FloorGetAllModel": [],
  "MyGPS.model.GPSuserModel": [],
  "MyGPS.model.GeofenceAlertHistory": [],
  "MyGPS.model.Layer.LayerBoundaryGetAllModel": [],
  "MyGPS.model.Layer.LayerGetAllModel": [],
  "MyGPS.model.ListOfMarkerModel": [],
  "MyGPS.model.MilageCountAlertHistory.MilageCountAlertHistory_LoadByDeviceAccNoModel": [],
  "MyGPS.model.MilageCountAlertHistory.MilageCountAlertHistory_LoadReceiptPictureByIDModel": [],
  "MyGPS.model.MilageCountInfo.MilageCountInfoLoad_ByAccountNoDeviceIDModel": [],
  "MyGPS.model.Place": [],
  "MyGPS.model.RegisterAccountModel": [],
  "MyGPS.model.RegisteredAccount.RegisteredAccountModel": [],
  "MyGPS.model.ResponderAlert.ResponderAlertModel": [],
  "MyGPS.model.ResponderAlertModel": [],
  "MyGPS.model.Sector.SectorGetAllModel": [],
  "MyGPS.model.Signal": [],
  "MyGPS.model.TraceAlert.TraceAlertHistoryModel": [],
  "MyGPS.model.TrackerDeviceModel": [],
  "MyGPS.model.TrackingHistory.TrackingHistoryModel": [],
  "MyGPS.model.TrackingItem": [],
  "MyGPS.model.TrackingItemAdjusted": [],
  "MyGPS.model.TrackingItemCheckIDmodel": [],
  "MyGPS.model.TrackingItemImage": [],
  "MyGPS.model.TrackingItemList.TrackingItemModel": [],
  "MyGPS.model.User.UserModel": [],
  "MyGPS.model.geoFenceAreaModel": [],
  "MyGPS.model.geoFenceModel": [],
  "MyGPS.model.markerModel": [],
  "MyGPS.model.multipleSignal": [],
  "MyGPS.model.multipletrackingsignal": [],
  "MyGPS.model.searchresultmodel": [],
  "MyGPS.model.settingModel": [],
  "MyGPS.model.signalhistorymodel": [],
  "MyGPS.model.signallastlocationmodel": [],
  "MyGPS.model.singlesignalTrackingmodel": [],
  "MyGPS.model.singlesignalmodel": [],
  "MyGPS.model.testlist": [],
  "MyGPS.store.AlertMilageCount.AlertMilageCountStore": [],
  "MyGPS.store.AutoFenceTimerGetByAcc": [],
  "MyGPS.store.AutoFenceTimerGetByID": [],
  "MyGPS.store.Building.BuildingStore": [],
  "MyGPS.store.Floor.FloorStore": [],
  "MyGPS.store.GPSuserStore": [
    "store.GPSuserStore"
  ],
  "MyGPS.store.GPSuserbyAccnostore": [
    "store.GPSuserStore"
  ],
  "MyGPS.store.GeofenceAlertHistoryGetByAcc": [],
  "MyGPS.store.GeofenceAlertHistoryStore": [
    "store.GeofenceAlertHistoryStore"
  ],
  "MyGPS.store.GpsUser.GpsUserStore": [
    "store.GpsUserStore"
  ],
  "MyGPS.store.Layer.LayerGetAllStore": [
    "store.LayerGetAllstore"
  ],
  "MyGPS.store.ListofMarkerStore": [],
  "MyGPS.store.MarkerloadAllstore": [
    "store.MarkerloadAllstore"
  ],
  "MyGPS.store.MilageCountAlertHistory.MilageCountAlertHistoryStore": [],
  "MyGPS.store.MilageCountInfo.MilageCountInfoStore": [],
  "MyGPS.store.Places": [],
  "MyGPS.store.RegisterAccountLatestIDstore": [
    "store.RegisterAccountLatestIDstore"
  ],
  "MyGPS.store.RegisterAccountStore": [
    "store.RegisterAccountStore"
  ],
  "MyGPS.store.RegisteredAccount.RegisteredAccountStore": [],
  "MyGPS.store.ResponderAlert.ResponderAlertStore": [],
  "MyGPS.store.ResponderAlertGetByAcc": [],
  "MyGPS.store.ResponderAlertGetByID": [
    "store.ResponderAlertGetByID"
  ],
  "MyGPS.store.Sector.SectorStore": [],
  "MyGPS.store.SignalItemList": [
    "store.SignalItemList"
  ],
  "MyGPS.store.TraceAlert.TraceAlertHistoryGetByAccNoTrackIDGeofenceID": [
    "store.GeofenceAlertHistoryStore"
  ],
  "MyGPS.store.TraceAlert.TraceAlertHistoryGetByAccNoYearMonth": [],
  "MyGPS.store.TrackerDevicestore": [],
  "MyGPS.store.TrackingHistoryMap.TrackingHistoryMapStore": [
    "store.TrackingHistoryMapStore"
  ],
  "MyGPS.store.TrackingItemCheckIDstore": [],
  "MyGPS.store.TrackingItemDetailstore": [],
  "MyGPS.store.TrackingItemImagestore": [],
  "MyGPS.store.TrackingItemList": [],
  "MyGPS.store.TrackingItemList.TrackingItemListsStore": [],
  "MyGPS.store.TrackingItemListAdjustedStore": [],
  "MyGPS.store.User.UserStore": [],
  "MyGPS.store.geoFenceActiveStore": [
    "store.geoFenceActiveStore"
  ],
  "MyGPS.store.geoFenceAreaSelectByAccNo": [
    "store.geoFenceAreaSelectByAccNo"
  ],
  "MyGPS.store.geoFenceAreaSelectByAccNoByFenceName": [
    "store.geoFenceAreaSelectByAccNoByFenceName"
  ],
  "MyGPS.store.geoFenceAreaSelectByIDByAccNo": [
    "store.geoFenceAreaSelectByIDByAccNo"
  ],
  "MyGPS.store.geoFenceStore": [
    "store.geoFenceStore"
  ],
  "MyGPS.store.getSearchColstore": [],
  "MyGPS.store.multipleSignalItemList": [
    "store.multipleSignalItemList"
  ],
  "MyGPS.store.multipletrackingitemselectF": [],
  "MyGPS.store.multipletrackingsignalpoint": [
    "store.multipletrackingsignalpoint"
  ],
  "MyGPS.store.settingGetbyAccontNo": [
    "store.settingGetbyAccontNo"
  ],
  "MyGPS.store.signalhistorystore": [
    "store.signalhistorystored"
  ],
  "MyGPS.store.signallastlocationstore": [
    "store.signallastlocationstore"
  ],
  "MyGPS.store.singlesignalTrackingstore": [
    "store.singlesignalTrackingstore"
  ],
  "MyGPS.store.singlesignalstore": [
    "store.singlesignalstores"
  ],
  "MyGPS.store.trackingitemhistorystore": [
    "store.trackingitemhistorystored"
  ],
  "MyGPS.view.Config.MilageCountInfo.GetCurrentData": [],
  "MyGPS.view.Config.TrackingHistoryMap.TrackingHistoryMapConfig": [],
  "MyGPS.view.Config.TrackingItems.TrackingItemsConfig": [],
  "MyGPS.view.Config.User.UserConfig": [],
  "MyGPS.view.Login": [
    "widget.loginpage"
  ],
  "MyGPS.view.Main": [
    "widget.main"
  ],
  "MyGPS.view.MainMenu": [
    "widget.mainmenu"
  ],
  "MyGPS.view.MainMenuUpgrade": [
    "widget.mainmenu"
  ],
  "MyGPS.view.MainPage": [
    "widget.mainPage"
  ],
  "MyGPS.view.MultiPleTracking.API.MultipleTrackingAPI": [],
  "MyGPS.view.MultiPleTracking.CustomePanel.MultiMapTrackingLayerNameCfmBox": [],
  "MyGPS.view.MultiPleTracking.CustomePanel.MultipleMapTrackingMenu": [],
  "MyGPS.view.MultiPleTracking.CustomePanel.MultipleMapTrackingSearchLocation": [],
  "MyGPS.view.MultiPleTracking.CustomePanel.MultipleMapTrackingSettingLayer": [],
  "MyGPS.view.MultipleTracking.multiTrackingItemsList": [
    "widget.multiTrackingItemsLists"
  ],
  "MyGPS.view.MultipleTracking.multiTrackingMap": [
    "widget.MultiTrackingMap"
  ],
  "MyGPS.view.MyAccount.RegistrationForm": [],
  "MyGPS.view.MyAccount.ResponderAlertList": [
    "widget.ResponderAlertList"
  ],
  "MyGPS.view.MyAccount.TrackieItems": [
    "widget.multitrackiUnderAcc"
  ],
  "MyGPS.view.MyAccount.UserAcc": [
    "widget.UserAccount"
  ],
  "MyGPS.view.MyAccount.listgeofTrackingitems": [
    "widget.listgeofTrackingitems"
  ],
  "MyGPS.view.MyAccount.singlesummary": [
    "widget.googlemapscard"
  ],
  "MyGPS.view.MyAccount.singlesummarypanel": [
    "widget.panelsinglesummary",
    "widget.todomapscard"
  ],
  "MyGPS.view.Setting.MainSetting": [
    "widget.listMainSetting"
  ],
  "MyGPS.view.Setting.MilageCountSetting": [],
  "MyGPS.view.Setting.SettingResponderAlert": [],
  "MyGPS.view.Setting.SettingTrackingItemList": [],
  "MyGPS.view.SettingFence.CustomePanel.SettingFenceAddNewfence": [],
  "MyGPS.view.SettingFence.CustomePanel.SettingFenceDrawFenceMenu": [],
  "MyGPS.view.SettingFence.CustomePanel.SettingFencePanelSettingInfo": [],
  "MyGPS.view.SettingFence.CustomePanel.SettingFencePanelSettingInfoSave": [],
  "MyGPS.view.SettingFence.CustomePanel.SettingFenceSearchLocation": [],
  "MyGPS.view.SettingFence.SettingFenceListOfGeoFence": [
    "widget.SettingFenceListOfGeoFence"
  ],
  "MyGPS.view.SettingFence.SettingFenceMap": [
    "widget.SettingFenceMap"
  ],
  "MyGPS.view.SingleTracking.CustomePanel.SingleTrackingMapVirtualFence_BurgerMenu": [],
  "MyGPS.view.SingleTracking.CustomePanel.SingleTrackingMap_PointInfo": [],
  "MyGPS.view.SingleTracking.CustomePanel.SingleTrackingWPSList": [],
  "MyGPS.view.SingleTracking.CustomePanel.SingleTrackingWPSListButton": [],
  "MyGPS.view.SingleTracking.SingleTrackingMapVirtualFence_Menus": [],
  "MyGPS.view.SingleTracking.holderSingleTrackingitem": [
    "widget.SingleTrackingholder"
  ],
  "MyGPS.view.SingleTracking.listSingleTrackingitem": [
    "widget.listSingleTrackingitem"
  ],
  "MyGPS.view.SingleTracking.singleTrackingMap": [
    "widget.SingleTrackingMap"
  ],
  "MyGPS.view.SingleTracking.singleTrackingOverViewMap": [
    "widget.WidgetsingleTrackingOverViewMap",
    "widget.singleTrackingOverViewMap"
  ],
  "MyGPS.view.SingleTrackingStreetView.SingleTrackingStreetViewMap": [
    "widget.SingleTrackingStreetViewMap"
  ],
  "MyGPS.view.TraceAlertFence.CustomePanel.TraceAlertFenceHistoryInfo": [],
  "MyGPS.view.TraceAlertFence.ListOfTraceAlertFence": [
    "widget.ListOfTraceAlertFence"
  ],
  "MyGPS.view.TraceAlertFence.TraceAlertFenceMap": [
    "widget.TraceAlertFenceMap"
  ],
  "MyGPS.view.TrackingHistory.TrackingHistoryCreateria": [
    "widget.TrackingHistoryCreateria"
  ],
  "MyGPS.view.TrackingHistory.TrackingHistoryMap": [
    "widget.HistoryMap"
  ],
  "MyGPS.view.TrackingHistory.TrackingHistoryMapInfoPanel": [],
  "MyGPS.view.TrackingHistory.TrackingHistoryMapPlayTrackedPanel": [],
  "MyGPS.view.TrackingHistory.TrackingHistoryMapTravelRangePanel": [],
  "MyGPS.view.about.aboutapp": [
    "widget.aboutapp"
  ],
  "MyGPS.view.about.abouts": [
    "widget.abouts"
  ],
  "MyGPS.view.about.panelabout": [
    "widget.panelabouts"
  ],
  "MyGPS.view.connection": [],
  "MyGPS.view.custompanel.SingelTrackingMap_MillageCount": [],
  "MyGPS.view.custompanel.SingelTrackingMap_MillageCountInfo": [],
  "MyGPS.view.custompanel.SingleTrackingMapStreetView_Menu": [],
  "MyGPS.view.custompanel.SingleTrackingMapStreetView_MiniMap": [],
  "MyGPS.view.custompanel.SingleTrackingMap_Menu": [],
  "MyGPS.view.custompanel.SingleTrackingMap_MilageCountAlertHistoryDetail": [],
  "MyGPS.view.custompanel.SingleTrackingMap_PointInfo": [],
  "MyGPS.view.custompanel.SingleTrackingMap_SpeedMeter": [],
  "MyGPS.view.custompanel.burgerMenu": [],
  "MyGPS.view.custompanel.dockOverViewMap": [
    "widget.dockOverViewMap"
  ],
  "MyGPS.view.custompanel.geofence_detailfencepanel": [],
  "MyGPS.view.custompanel.geofence_rightpanel": [],
  "MyGPS.view.custompanel.geofence_rightpanelSettingDrawFence": [],
  "MyGPS.view.custompanel.master_usermanual": [
    "widget.usermanual"
  ],
  "MyGPS.view.custompanel.multiTracking_InfoPanel": [],
  "MyGPS.view.custompanel.overViewMapStreetViewLiveTracking": [],
  "MyGPS.view.custompanel.singleStreetViewTrackingMap_rightpanel": [],
  "MyGPS.view.custompanel.singleTrackingMap_Search": [],
  "MyGPS.view.custompanel.singleTrackingMap_rightpanel": [],
  "MyGPS.view.custompanel.splashLogo": [
    "widget.splashLogo"
  ],
  "MyGPS.view.functionality.funct": [],
  "MyGPS.view.functionality.routine": [],
  "MyGPS.view.geoFences.geoFenceDB": [],
  "MyGPS.view.geoFences.geofence": [
    "widget.mapGeofence"
  ],
  "MyGPS.view.geoFences.holdergeofence": [
    "widget.geoFencesholder"
  ],
  "MyGPS.view.geoFences.listgeofenceArea": [
    "widget.listgeofenceArea"
  ],
  "MyGPS.view.geoFences.listgeofenceitem": [
    "widget.listgeofenceitems"
  ],
  "MyGPS.view.markerwithlabel": []
});
